# Copyright (c) 2024, 2025, Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
# spell-checker: ignore ocid ecpu

title: "Oracle AI Optimizer and Toolkit"
description: "Explore the capabilities of AI with the Oracle Database."
informationalText: "https://oracle-samples.github.io/ai-optimizer/"
schemaVersion: 1.1.0
version: "20190304"
logoUrl: https://github.com/oracle-samples/ai-optimizer/blob/main/src/client/media/logo_130_130.png
locale: "en"

variableGroups:
  #########################################################################
  # Hidden
  #########################################################################
  - title: "Default Hidden"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - current_user_ocid
      - fingerprint
      - private_key_path
      - private_key
    visible: false

  - title: "Hidden (Defaults)"
    variables:
      - adb_version
      - k8s_version
      - compute_os_ver
    visible: false

  #########################################################################
  # General
  #########################################################################
  - title: "AI Optimizer"
    variables:
      - compartment_ocid
      - label_prefix
      - infrastructure
    visible: true

  #########################################################################
  # Infrastructure - Kubernetes
  #########################################################################
  - title: "Kubernetes Infrastructure Options"
    variables:
      - k8s_api_is_public
      - k8s_api_endpoint_allowed_cidrs
      - k8s_cpu_node_pool_size
      - compute_cpu_ocpu
      - compute_cpu_shape
      - k8s_node_pool_gpu_deploy
      - k8s_gpu_node_pool_size
      - compute_gpu_shape
    visible:
      eq:
        - infrastructure
        - "Kubernetes"

  #########################################################################
  # Infrastructure - Virtual Machine
  #########################################################################
  - title: "Virtual Machine Infrastructure Options"
    variables:
      - vm_gpu_enabled
      - compute_cpu_shape
      - compute_cpu_ocpu
      - compute_gpu_shape
    visible:
      eq:
        - infrastructure
        - "VM"

  #########################################################################
  # Load Balancer
  #########################################################################
  - title: "Load Balancers Options"
    variables:
      - lb_min_shape
      - lb_max_shape
      - client_allowed_cidrs
      - server_allowed_cidrs
    visible: true

  #########################################################################
  # Database
  #########################################################################
  - title: "Database Options"
    variables:
      - adb_license_model
      - adb_edition
      - adb_whitelist_cidrs
      - adb_ecpu_core_count
      - adb_is_cpu_auto_scaling_enabled
      - adb_data_storage_size_in_gb
      - adb_is_storage_auto_scaling_enabled
    visible: true

###########################################################################
variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    required: true

  label_prefix:
    type: string
    title: "Application Name"
    pattern: "^$|^[